
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'My Awesome Blog',
  description: 'Generated by create Next + Sanity + Typescript + Tailwind',
  icons: {
    icon: "/favico.png",
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body>
        {children}
    </body>
    </html>
)
}
