import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import Link from 'next/link'
import { getPages } from '@/sanity/sanity-utilis'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'My Awesome Blog',
  description: 'Generated by create Next + Sanity + Typescript + Tailwind',
  icons: {
    icon: "/favico.png",
  },
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const pages = await getPages();

  return (
    <html lang="en">
      <body className="max-w-3xl mx-auto py-10">

        <header className='flex items-center justify-between'>
          <Link href="/"
          className="bg-gradient-to-r from-orange-400 via-red-600 to-purple-700 bg-clip-text text-transparent text-lg font-bold"
          >Home</Link>

          <div className='flex items-center gap-5 text-sm text-gray-700'>
            {pages.map((page) =>(
              <Link key={page._id} 
              href={`/${page.slug}`} className="hover:underline">
                {page.title}
              </Link>
            ))}
          </div>
          
        </header>

        <main className="py-10">
        {children}
        </main>
      </body>
    </html>
  )
}
